tasks:
  - name: "Set up and run frontend"
    env:
      SITE_ENV: 'dev'
    init: npm run rebuild
    command: npm run serve

ports:
  - port: 8080
    onOpen: open-browser
    visibility: private

vscode:
  extensions:
    - Catppuccin.catppuccin-vsc
    - DavidAnson.vscode-markdownlint
    - dbaeumer.vscode-eslint
    - ecmel.vscode-html-css
    - esbenp.prettier-vscode
    - eseom.nunjucks-template
    - sissel.shopify-liquid
