name: Index Entities and Extract Events

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9,13,18 * * *"

jobs:
  index-entities:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./apps/entities

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: release

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Fetch edition branch
        run: npm run fetch

      - name: Index entities
        run: npm run build

      - name: Commit and push
        if: ${{ true }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated entities indexing

  extract-events:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: ./apps/events

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: release

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Extract events
        run: npm run build

      - name: Commit and push
        if: ${{ true }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated events extraction
