name: Index Entities

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9,13,18 * * *"

jobs:
  index-entities:
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./apps/entities

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: release

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Fetch edition branch
        run: npm run fetch

      - name: Index enities
        run: npm run build

      - name: Commit and push
        if: ${{ true }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Entities Indexing
