name: Publish TEI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9,13,18 * * *"

jobs:
  publish-tei:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: dts

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install && npm update

      - name: Static DTS generation
        run: |
          npm run static

      - name: Commit and push
        if: ${{ true }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated DTS publication
