name: Validate TEI

on:
  push:
    branches:
      - edition

jobs:
  xml-linters:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download schema
      run: wget http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng
    - name: Lint book_one.xml
      uses: ChristophWurst/xmllint-action@master
      with:
        xml-file: ./texts/book_one/book_one.xml
        xml-schema-file: ./tei_all.rng
        xml-schema-type: relaxng
